### PR TITLE
Provide relation info in nested params

### PR DESCRIPTION
**Pull request by Tenrys**
This allows to do something like this:

```ts
import { Prisma } from "@prisma/client";
import { NestedParams } from "prisma-nested-middleware";

const archivedField = "archivedAt" as const;
type Model = Omit<Prisma.DMMF.Model, "fields"> & {
	fields: Record<string, Prisma.DMMF.Field>;
};
const models = Prisma.dmmf.datamodel.models.reduce((acc, model) => {
	acc[model.name as Prisma.ModelName] = {
		...model,
		fields: model.fields.reduce((acc, field) => {
			acc[field.name] = field;
			return acc;
		}),
	};
	return acc;
}, {} as Record<Prisma.ModelName, Model>);
const modelsWithArchivedAt = Object.fromEntries(
	Object.entries(models).filter(([, model]) => model.fields[archivedField])
);

export default (params: NestedParams) => {
	if (!params.model) return;

	if (["count", "findFirst", "findMany", "update", "updateMany", "select"].includes(params.action)) {
		if (modelsWithArchivedAt[params.model]) {
			if (params.action == "update") params.action = "updateMany";
			if (params.action == "select" && !params.relation?.isList) return;
			if (!params.args.where) params.args.where = {};
			if (params.args.where[archivedField] == undefined) {
				params.args.where[archivedField] = null;
			}
		}
	}
};
```

This line in particular:

```ts
if (params.action == "select" && !params.relation?.isList) return;
```

### CODE REVIEW

**Comment by olivierwilkinson** [comment]
Hi there 👋 I actually have a new major release in the works that includes relations in the params along with some other new features. I'm doing some final cleanup of it so it should be out this weekend, I'll leave this open for the meantime so that we can chat on here about if the new release works for your use case 😄

**Comment by olivierwilkinson** [comment]
Heya,

The major version I was hoping to release needs some more work before it's ready to go out so I've released a minor version that includes the relation info in params 😄, it is available in [v2.3.0](https://github.com/olivierwilkinson/prisma-nested-middleware/releases/tag/v2.3.0).

I'm still hoping to get the major version out in the next few days as long as there are no other wrinkles. Also just to give you a heads up, in tha version I've restructured the params so that the `scope` object includes the relation info so if you don't have any pressing need to upgrade it might be worth waiting for that to land.

**Comment by Tenrys** [comment]
So, with 2.3.0 the relation is alongside `scope` in the params, but in the next major version it'll be within `scope`, yes?

**Comment by olivierwilkinson** [comment]
> So, with 2.3.0 the relation is alongside `scope` in the params, but in the next major version it'll be within `scope`, yes?

Exactly right 👍 

The next major version adds quite a few new things to NestedParams so it made sense to update the scope object to accomodate them, roughly it will look like this:

```typescript
type Scope = {
  parentParams: NestedParams,
  relation: Prisma.DMMF.Field,
  ...[other fields]
}

**Comment by olivierwilkinson** [comment]
Heya 👋 

I've released [v3](https://github.com/olivierwilkinson/prisma-nested-middleware/releases/tag/v3.0.0), it ended up slightly differently to what I described here: I realised that in one of my middleware it would be useful to know the relation from the current model back to it's parent, so I've included that in the scope object as well.

The new scope object has the following structure:
```typescript
type Scope = {
  parentParams: NestedParams;
  relations: { to: Prisma.DMMF.Field; from: Prisma.DMMF.Field };
  ...[where action fields]
};
```

In order to do what you outlined above you would use `scope.relations.to` since that is the relation from the parent to the current model. The `scope.relations.from` field is the relation from the model back to it's parent.

I hope you find the new version useful, there are quite a few new features so check out the readme. Please let me know if you find any issues! 😄

**Pull request closed without merging**
